#!/usr/bin/env python3.6
def bin_search(arr,ele):
  if len(arr) == 0:
    return False
  else:
    mid = len(arr)//2
    if arr[mid] == ele:
      return True
    else:
      if ele < arr[mid]:
        return bin_search(arr[:mid],ele)
      else:
        return bin_search(arr[mid+1:],ele)

print(bin_search([1,3,5,6,8,11,15,17],7))


