#!/usr/bin/env python3.6
def bin_search(arr,ele):
  first = 0
  last = len(arr)-1
  found = False
  while first <= last and not found:
    mid = (first+last)//2
    if arr[mid] == ele:
        found = True
    else:
        if ele < arr[mid]:
            last = mid - 1
        else:
            first = mid + 1
  return found

print(bin_search([1,4,7,8,9,15,16],6))
