#!/usr/bin/env python3.6

def finder(arr1,arr2):
  arr1.sort()
  arr2.sort()

  for num1, num2 in zip(arr1,arr2):
    if num1 != num2:
      return num1       # num1 is the missing element

  return arr1[-1] #otherwise return the last element of first array

print(finder([1,2,3,4,4,5,6],[3,1,2,4,6,5]))


