#!/usr/bin/env python3.6

def is_palindrome(s):
  return all(s[i] == s[~i] for i in range(len(s)//2))

print(is_palindrome("tattarrattat"))

#~ is the bitwise complement operator in python which essentially calculates -x - 1
#So for i = 0 it would compare s[0] with s[len(s) - 1], for i = 1, s[1] with s[len(s) - 2]

#all will return True only when all the elements are True
