#!/usr/bin/env python3.6
def seq_search(arr,ele):
  pos = 0
  found = False
  stopped = False
  while pos < len(arr) and not found and not stopped:
    if arr[pos] == ele:
      found = True
    elif arr[pos] > ele:
      stopped = True
    else:
      pos += 1
  return found

print(seq_search([1,3,4,6,7,8],5))
