#!/usr/bin/env python3.6
def seq_search(arr,ele):
  pos = 0
  found = False
  while pos<len(arr) and not found:
    if arr[pos] == ele:
      found = True
    else:
      pos += 1
  return found

print(seq_search([2,7,1,6,5],9))
